"""Verify gruff-py's fingerprint matches gruff-php's byte-for-byte.

Expected values were generated by running gruff-php's `Finding::fingerprint()` against
the inputs below and are baked in as ground truth — a regression in either side breaks
the test, which is the point.
"""

import pytest

from gruffpy.finding.fingerprint import fingerprint_for

PHP_GROUND_TRUTH = [
    # (rule_id, file, line, end_line, column, symbol, expected_fingerprint)
    ("size.file-length", "src/foo.py", 1, 42, None, None, "ba3021b8dddebe34"),
    ("docs.todo-density", "path/with/slashes.py", None, None, None, None, "9f7887f2d6278393"),
    ("security.eval-call", "tests/test_a.py", 5, 5, 10, "test_eval", "9b81f131149d2b99"),
    ("sensitive-data.aws-access-key", "config/.env", 7, 7, None, None, "75ff0dcd32c358da"),
    ("size.file-length", "src/long_file.py", 1, 900, None, None, "9633df2ac29dcda4"),
]


@pytest.mark.parametrize(
    "rule_id,file,line,end_line,column,symbol,expected",
    PHP_GROUND_TRUTH,
)
def test_fingerprint_matches_php(rule_id, file, line, end_line, column, symbol, expected):
    actual = fingerprint_for(
        rule_id=rule_id,
        file_path=file,
        line=line,
        end_line=end_line,
        column=column,
        symbol=symbol,
    )
    assert actual == expected


def test_fingerprint_is_16_lowercase_hex_chars():
    fp = fingerprint_for("r", "f", 1)
    assert len(fp) == 16
    assert all(c in "0123456789abcdef" for c in fp)


def test_fingerprint_is_deterministic():
    assert fingerprint_for("r", "f", 1, 1, 1, "s") == fingerprint_for("r", "f", 1, 1, 1, "s")


def test_fingerprint_distinguishes_lines():
    assert fingerprint_for("r", "f", 1) != fingerprint_for("r", "f", 2)


def test_fingerprint_distinguishes_files():
    assert fingerprint_for("r", "a", 1) != fingerprint_for("r", "b", 1)


def test_fingerprint_distinguishes_rule_ids():
    assert fingerprint_for("a", "f", 1) != fingerprint_for("b", "f", 1)


def test_fingerprint_distinguishes_symbols():
    assert fingerprint_for("r", "f", 1, symbol="a") != fingerprint_for("r", "f", 1, symbol="b")


def test_fingerprint_does_not_depend_on_unhashed_fields():
    """Severity, confidence, pillar, message, metadata are NOT in the fingerprint —
    rewording rule messages must not churn baselines."""
    # Same identifying fields, different non-hashed context: same fingerprint.
    fp_a = fingerprint_for("r", "f", 1, end_line=1, column=1, symbol="s")
    fp_b = fingerprint_for("r", "f", 1, end_line=1, column=1, symbol="s")
    assert fp_a == fp_b
