import pytest

from gruffpy.rule.docs.ignore_directive_reason_rule import IgnoreDirectiveReasonRule
from tests.unit.rule.docs._helpers import default_ctx, make_unit


def test_noqa_without_reason_emits():
    src = "import os  # noqa\n"

    findings = IgnoreDirectiveReasonRule().analyse(make_unit(src), default_ctx())

    assert len(findings) == 1
    assert findings[0].metadata == {"directive": "noqa", "reasonPresent": False, "reason": ""}


def test_noqa_with_substantive_reason_is_skipped():
    src = "from package import name  # noqa: F401 - re-exported public API\n"

    assert IgnoreDirectiveReasonRule().analyse(make_unit(src), default_ctx()) == []


def test_type_ignore_with_generic_reason_still_emits():
    src = "value = plugin.attr  # type: ignore[attr-defined]  # ignore\n"

    findings = IgnoreDirectiveReasonRule().analyse(make_unit(src), default_ctx())

    assert len(findings) == 1
    assert findings[0].metadata["directive"] == "type: ignore[attr-defined]"
    assert findings[0].metadata["reasonPresent"] is True
    assert findings[0].metadata["reason"] == "ignore"


def test_pragma_no_cover_with_double_dash_reason_is_skipped():
    src = "if __name__ == '__main__':  # pragma: no cover -- subprocess smoke only\n    pass\n"

    assert IgnoreDirectiveReasonRule().analyse(make_unit(src), default_ctx()) == []


def test_gruff_disable_without_reason_emits():
    src = "# gruff: disable=docs.missing-function-docstring\n"

    findings = IgnoreDirectiveReasonRule().analyse(make_unit(src), default_ctx())

    assert len(findings) == 1
    assert findings[0].metadata["directive"] == "gruff: disable=docs.missing-function-docstring"


def test_directive_inside_string_literal_is_skipped():
    src = "text = '# noqa'\n"

    assert IgnoreDirectiveReasonRule().analyse(make_unit(src), default_ctx()) == []


def test_generated_file_is_skipped():
    """Skip a file whose header says it is generated, the SQLAlchemy ``sync_test_files.py`` output shape."""
    src = (
        '"""This file is automatically generated from test_typed_mapping.py.\n\n'
        'Do not edit manually, any change will be lost.\n"""  # noqa: E501\n\n'
        "import os  # noqa\n"
    )

    assert IgnoreDirectiveReasonRule().analyse(make_unit(src), default_ctx()) == []


@pytest.mark.parametrize(
    "source",
    [
        "headers = request.headers  # type: ignore[arg-type]  # urllib3#3072\n",
        "from package import name  # noqa: F401 - see mypy#4125\n",
        "value = legacy()  # type: ignore -- GH-1234\n",
    ],
    ids=["second-comment-tracker", "dash-reason-tracker", "tracker-key"],
)
def test_tracker_reference_is_a_substantive_reason(source: str) -> None:
    """Accept an issue reference as the rationale, as requests' ``adapters.py`` writes it.

    Args:
        source: Suppressed line whose reason is a tracker reference.
    """
    assert IgnoreDirectiveReasonRule().analyse(make_unit(source), default_ctx()) == []


def test_noqa_codes_do_not_swallow_a_neighbouring_tool_directive():
    """Report pytest's noqa-plus-isort line with honest metadata: the directive, and no reason."""
    src = "from _pytest.assertion.util import format_explanation  # noqa:F401, isort:skip\n"

    findings = IgnoreDirectiveReasonRule().analyse(make_unit(src), default_ctx())

    assert len(findings) == 1
    assert findings[0].metadata == {"directive": "noqa:F401", "reasonPresent": False, "reason": ""}
