"""Exercise Boolean annotation shapes as users encounter them in scan results.

The matrix pairs scalar findings with container and callable collisions so a
reviewer can see exactly which declarations receive naming guidance. Quoted
annotations are parsed as source text only and never imported or evaluated.
"""

import ast

import pytest

from gruffpy.config.analysis_config import AnalysisConfig
from gruffpy.config.rule_settings import RuleSettings
from gruffpy.finding.finding import Finding
from gruffpy.parser.analysis_unit import AnalysisUnit
from gruffpy.rule.context import RuleContext
from gruffpy.rule.naming.boolean_prefix_rule import BooleanPrefixRule
from gruffpy.source.source_file import SourceFile

_DECLARATION_CASES = (
    pytest.param(
        "def status() -> {annotation}:\n    return None\n",
        "function",
        id="function-return",
    ),
    pytest.param(
        "class Record:\n    status: {annotation} = None\n",
        "attribute",
        id="annotated-attribute",
    ),
)

_SCALAR_ANNOTATION_CASES = (
    pytest.param("bool", "bool", id="bool"),
    pytest.param('"bool"', "bool", id="quoted-bool"),
)

_OPTIONAL_ANNOTATION_CASES = (
    pytest.param("Optional[bool]", id="optional"),
    pytest.param("typing.Optional[bool]", id="typing-optional"),
    pytest.param("bool | None", id="bool-or-none"),
    pytest.param("None | bool", id="none-or-bool"),
    pytest.param("Union[bool, None]", id="union"),
    pytest.param("typing.Union[None, bool]", id="typing-union"),
    pytest.param('"Optional[bool]"', id="quoted-optional"),
    pytest.param('"typing.Optional[bool]"', id="quoted-typing-optional"),
    pytest.param('"bool | None"', id="quoted-pep604"),
)

_ANNOTATED_ANNOTATION_CASES = (
    pytest.param("Annotated[bool, 1]", id="annotated-bool"),
    pytest.param("typing.Annotated[bool, 1]", id="typing-annotated-bool"),
    pytest.param("Annotated[Optional[bool], 1]", id="annotated-optional"),
    pytest.param(
        "typing.Annotated[typing.Optional[bool], 1]",
        id="typing-annotated-optional",
    ),
    pytest.param('"Annotated[Optional[bool], 1]"', id="quoted-annotated-optional"),
)

_CONTAINER_AND_OTHER_ANNOTATION_CASES = (
    pytest.param("tuple[bool, str]", id="tuple-mixed"),
    pytest.param("tuple[bool, bool]", id="tuple-bool"),
    pytest.param("list[bool]", id="list"),
    pytest.param("set[bool]", id="set"),
    pytest.param("dict[str, bool]", id="dict"),
    pytest.param("Iterator[bool]", id="iterator"),
    pytest.param("Iterable[bool]", id="iterable"),
    pytest.param("Generator[bool, None, None]", id="generator"),
    pytest.param("Union[bool, str]", id="mixed-union"),
    pytest.param("typing.Union[str, bool]", id="typing-mixed-union"),
    pytest.param("Box[bool]", id="arbitrary-generic"),
    pytest.param('"tuple[bool, str]"', id="quoted-tuple"),
)

_CALLABLE_ANNOTATION_CASES = (
    pytest.param("Callable[..., bool]", id="typing-callable"),
    pytest.param("collections.abc.Callable[[str], bool]", id="collections-callable"),
    pytest.param('"Callable[..., bool]"', id="quoted-callable"),
)

_OVER_LIMIT_ANNOTATION_WRAPPERS = 40


def _unit(source: str, display_path: str = "x.py") -> AnalysisUnit:
    """Parse one user file into the same analysis unit the CLI scans.

    Args:
        source: Python source entered or generated by the user; empty text is
            valid input but contains no declarations.
        display_path: User-visible report path; an empty path means the report
            cannot identify the source file and is not used by these tests.

    Returns:
        Parsed unit with parent links needed by declaration exemptions.
    """
    tree = ast.parse(source)
    # A user's declaration needs its enclosing class/module context for exemptions.
    for parent_node in ast.walk(tree):
        # Each child receives the parent link production parsing supplies later.
        for child_node in ast.iter_child_nodes(parent_node):
            child_node.parent = parent_node  # type: ignore[attr-defined]  # AST parent links
    return AnalysisUnit(
        file=SourceFile(absolute_path=f"/{display_path}", display_path=display_path, type="python"),
        source=source,
        tree=tree,
    )


def _ctx(options: dict | None = None) -> RuleContext:
    """Build the user's active Boolean-rule settings for one scan.

    Args:
        options: Exact configured options; ``None`` means registry defaults,
            while an empty mapping means the user supplied no overrides.

    Returns:
        Rule context ready to analyse the in-memory user file.
    """
    rule = BooleanPrefixRule()
    # No supplied options means the user accepts the registered defaults.
    configured_options = {} if options is None else options
    return RuleContext(
        project_root="/",
        config=AnalysisConfig(
            rules={rule.definition().id: RuleSettings(enabled=True, options=configured_options)}
        ),
    )


def _findings_for_annotation(
    annotation: str,
    declaration_template: str,
) -> list[Finding]:
    """Return the naming guidance shown for one user annotation/declaration pair.

    Args:
        annotation: Annotation source spelling; empty text is invalid Python
            and therefore is not a supported user declaration here.
        declaration_template: Function or attribute source template containing
            the ``{annotation}`` insertion point.

    Returns:
        Findings shown to the user; empty means the shape is not scalar Boolean.
    """
    user_source = declaration_template.format(annotation=annotation)
    return BooleanPrefixRule().analyse(_unit(user_source, "sample.py"), _ctx())


@pytest.mark.parametrize(("declaration_template", "declaration_kind"), _DECLARATION_CASES)
@pytest.mark.parametrize(("annotation", "expected_shape"), _SCALAR_ANNOTATION_CASES)
def test_scalar_boolean_annotation_shape_fires(
    declaration_template: str,
    declaration_kind: str,
    annotation: str,
    expected_shape: str,
) -> None:
    """Show naming guidance for direct scalar Boolean functions and attributes.

    Args:
        declaration_template: Function/attribute source shown to the scanner.
        declaration_kind: Expected user-facing metadata kind.
        annotation: Direct or quoted scalar Boolean spelling.
        expected_shape: Stable metadata value the report must explain.
    """
    findings = _findings_for_annotation(annotation, declaration_template)

    assert len(findings) == 1
    assert findings[0].metadata == {
        "identifier": "status",
        "kind": declaration_kind,
        "annotationShape": expected_shape,
    }


@pytest.mark.parametrize(("declaration_template", "declaration_kind"), _DECLARATION_CASES)
@pytest.mark.parametrize("annotation", _OPTIONAL_ANNOTATION_CASES)
def test_optional_boolean_annotation_shapes_fire(
    declaration_template: str,
    declaration_kind: str,
    annotation: str,
) -> None:
    """Show the same guidance for exact optional Boolean spellings.

    Args:
        declaration_template: Function/attribute source shown to the scanner.
        declaration_kind: Expected user-facing metadata kind.
        annotation: Exact optional spelling under review.
    """
    findings = _findings_for_annotation(annotation, declaration_template)

    assert len(findings) == 1
    assert findings[0].metadata["kind"] == declaration_kind
    assert findings[0].metadata["annotationShape"] == "optional-bool"


@pytest.mark.parametrize(("declaration_template", "declaration_kind"), _DECLARATION_CASES)
@pytest.mark.parametrize("annotation", _ANNOTATED_ANNOTATION_CASES)
def test_annotated_boolean_annotation_shapes_fire(
    declaration_template: str,
    declaration_kind: str,
    annotation: str,
) -> None:
    """Show guidance when metadata wraps a scalar or optional Boolean.

    Args:
        declaration_template: Function/attribute source shown to the scanner.
        declaration_kind: Expected user-facing metadata kind.
        annotation: Exact Annotated spelling under review.
    """
    findings = _findings_for_annotation(annotation, declaration_template)

    assert len(findings) == 1
    assert findings[0].metadata["kind"] == declaration_kind
    assert findings[0].metadata["annotationShape"] == "annotated-bool"


@pytest.mark.parametrize(("declaration_template", "_declaration_kind"), _DECLARATION_CASES)
@pytest.mark.parametrize("annotation", _CONTAINER_AND_OTHER_ANNOTATION_CASES)
def test_container_and_other_boolean_annotation_shapes_stay_quiet(
    declaration_template: str,
    _declaration_kind: str,
    annotation: str,
) -> None:
    """Keep container members and mixed unions out of scalar naming guidance.

    Args:
        declaration_template: Function/attribute source shown to the scanner.
        _declaration_kind: Parametrized label unused because no finding is expected.
        annotation: Container, mixed union, or arbitrary generic spelling.
    """
    assert _findings_for_annotation(annotation, declaration_template) == []


@pytest.mark.parametrize(("declaration_template", "_declaration_kind"), _DECLARATION_CASES)
@pytest.mark.parametrize("annotation", _CALLABLE_ANNOTATION_CASES)
def test_callable_boolean_annotation_shapes_stay_quiet(
    declaration_template: str,
    _declaration_kind: str,
    annotation: str,
) -> None:
    """Keep callable return parameters from masquerading as scalar results.

    Args:
        declaration_template: Function/attribute source shown to the scanner.
        _declaration_kind: Parametrized label unused because no finding is expected.
        annotation: Callable spelling whose own result happens to be Boolean.
    """
    assert _findings_for_annotation(annotation, declaration_template) == []


@pytest.mark.parametrize(("declaration_template", "declaration_kind"), _DECLARATION_CASES)
def test_future_annotations_keep_structural_optional_shape(
    declaration_template: str,
    declaration_kind: str,
) -> None:
    """Keep future-annotations source deterministic without runtime resolution.

    Args:
        declaration_template: Function/attribute source shown to the scanner.
        declaration_kind: Expected user-facing metadata kind.
    """
    user_source = "from __future__ import annotations\n" + declaration_template.format(
        annotation="Optional[bool]"
    )

    findings = BooleanPrefixRule().analyse(_unit(user_source), _ctx())

    assert len(findings) == 1
    assert findings[0].metadata["kind"] == declaration_kind
    assert findings[0].metadata["annotationShape"] == "optional-bool"


@pytest.mark.parametrize(
    "annotation",
    [
        pytest.param('"bool["', id="invalid-syntax"),
        pytest.param('"dangerous_call()"', id="call-expression"),
    ],
)
def test_quoted_annotation_parse_failures_and_calls_stay_quiet(annotation: str) -> None:
    """Treat invalid or executable-looking quoted text as unproved user input.

    Args:
        annotation: Quoted invalid/call-shaped source; empty findings are expected.
    """
    assert _findings_for_annotation(annotation, _DECLARATION_CASES[0].values[0]) == []


def test_annotation_depth_limit_stays_quiet() -> None:
    """Stop deeply wrapped annotations before a crafted file exhausts the scanner."""
    # A generated model can nest metadata repeatedly; excessive depth is unproved.
    deeply_wrapped_annotation = (
        "Annotated[" * _OVER_LIMIT_ANNOTATION_WRAPPERS
        + "bool"
        + ", 1]" * _OVER_LIMIT_ANNOTATION_WRAPPERS
    )

    assert (
        _findings_for_annotation(deeply_wrapped_annotation, _DECLARATION_CASES[0].values[0]) == []
    )


def test_scalar_boolean_annotation_keeps_survivor_identity() -> None:
    """Keep an existing user's baseline identity while adding shape explanation."""
    finding = _findings_for_annotation("bool", _DECLARATION_CASES[0].values[0])[0]

    assert finding.fingerprint() == "55c475836528ae94"
    assert finding.stable_identity() == "29b6e4cbadf5b918"
    assert finding.metadata["annotationShape"] == "bool"


def test_bool_return_without_prefix_fires():
    src = "def status(x) -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert len(findings) == 1
    assert findings[0].metadata["identifier"] == "status"


def test_is_prefix_does_not_fire():
    src = "def is_valid(x) -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_has_prefix_does_not_fire():
    src = "def has_value() -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_verb_predicate_does_not_fire():
    src = (
        "def uses_quoted_placeholder() -> bool:\n"
        "    return True\n"
        "def check_rules_markdown() -> bool:\n"
        "    return True\n"
    )
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_bool_adjective_attribute_does_not_fire():
    src = "class C:\n    enabled: bool = True\n    report_interactive: bool = False\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_flag_prefix_and_suffix_patterns_do_not_fire():
    src = (
        "class C:\n"
        "    include_ignored: bool = True\n"
        "    no_config: bool = False\n"
        "    query_bool: bool = True\n"
        "    feature_flag: bool = False\n"
    )
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_test_files_are_exempt():
    src = "def _number_is_rendered() -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src, "tests/unit/test_widget.py"), _ctx())
    assert findings == []


def test_can_prefix_does_not_fire():
    src = "def can_edit() -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_no_return_annotation_does_not_fire():
    src = "def valid(x):\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_non_bool_return_does_not_fire():
    src = "def name() -> str:\n    return 'x'\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_optional_bool_return_fires():
    src = "from typing import Optional\ndef maybe_status() -> Optional[bool]:\n    return None\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert len(findings) == 1


def test_bool_or_none_return_fires():
    src = "def maybe_status() -> bool | None:\n    return None\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert len(findings) == 1


def test_string_annotation_fires():
    src = 'def status() -> "bool":\n    return True\n'
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert len(findings) == 1


def test_bool_typed_attribute_fires():
    src = "class C:\n    status: bool = True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert len(findings) == 1
    assert findings[0].metadata["kind"] == "attribute"


def test_bool_typed_attribute_with_prefix_does_not_fire():
    src = "class C:\n    is_valid: bool = True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_override_decorator_skips_rule():
    src = (
        "from typing import override\n"
        "class C:\n"
        "    @override\n"
        "    def valid(self) -> bool:\n"
        "        return True\n"
    )
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_dunder_skipped():
    src = "class C:\n    def __bool__(self) -> bool:\n        return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_upper_snake_module_constant_does_not_fire():
    # Module-level all-caps constants follow Python convention; renaming
    # `ENABLE_PROMPT_CACHE: bool = True` to `is_prompt_cache_enabled` would
    # break the convention.
    src = "ENABLE_PROMPT_CACHE: bool = True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_pydantic_basemodel_field_does_not_fire():
    # Pydantic field name is part of the JSON API contract; rename would break
    # every consumer.
    src = (
        "from pydantic import BaseModel\n"
        "class SuggestedAction(BaseModel):\n"
        "    actioned: bool = False\n"
    )
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_typeddict_field_does_not_fire():
    src = (
        "from typing import TypedDict\n"
        "class Session(TypedDict, total=False):\n"
        "    skip_verification: bool\n"
    )
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_dataclass_field_does_not_fire():
    src = "from dataclasses import dataclass\n@dataclass\nclass Cfg:\n    actioned: bool = False\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_plain_class_bool_field_still_fires():
    # Sanity: the schema exemption is keyed on framework bases / dataclass
    # decorator. A plain class with a bool attribute is NOT exempt.
    src = "class Service:\n    actioned: bool = False\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert len(findings) == 1


def test_looks_like_prefix_does_not_fire():
    # `looks_like_*` is a verb-shaped English predicate; counts as boolean-prefixed.
    src = "def _looks_like_phone(s: str) -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_affirms_suffix_does_not_fire():
    src = "def _slot_prompt_affirms(s: str) -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_declines_suffix_does_not_fire():
    src = "def _slot_prompt_declines(s: str) -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_classify_verb_still_fires():
    # Sanity: not every verb is a predicate. `classify` returns a label, not
    # a bool - a function called `_classify_caller_phone` that returns bool
    # legitimately deserves the rename suggestion. Proves the verb allowlist
    # didn't over-broaden into "every verb".
    src = "def _classify_caller_phone(p: str) -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert len(findings) == 1


def test_default_exact_boolean_names_do_not_fire():
    src = "def ok() -> bool:\n    return True\ndef force() -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(_unit(src), _ctx())
    assert findings == []


def test_configured_exact_boolean_name_does_not_fire():
    src = "def locked() -> bool:\n    return True\n"
    findings = BooleanPrefixRule().analyse(
        _unit(src),
        _ctx(options={"acceptedBooleanNames": ["locked"]}),
    )
    assert findings == []


@pytest.mark.parametrize(
    "declaration_name",
    [
        pytest.param("_query_guard_alive", id="query-guard"),
        pytest.param("_source_groups_alive", id="source-groups"),
    ],
)
def test_final_alive_predicates_do_not_fire(declaration_name: str) -> None:
    """Keep final ``alive`` predicates out of the user's naming report.

    Args:
        declaration_name: Liveness check the user chose for a scalar Boolean.
    """
    # A user may expose an internal health check without an ``is_`` prefix.
    user_source = f"def {declaration_name}() -> bool:\n    return True\n"

    user_findings = BooleanPrefixRule().analyse(_unit(user_source), _ctx())

    assert user_findings == []


def test_alive_before_result_still_fires() -> None:
    """Keep an action-result name visible in the user's naming report."""
    # A user may return whether a liveness operation succeeded, not live state.
    user_source = "def alive_result() -> bool:\n    return True\n"

    user_findings = BooleanPrefixRule().analyse(_unit(user_source), _ctx())

    assert len(user_findings) == 1
    assert user_findings[0].metadata["identifier"] == "alive_result"


@pytest.mark.parametrize(
    "declaration_name",
    [
        pytest.param("_source_text_contains", id="source-text"),
        pytest.param("_query_contains", id="query"),
    ],
)
def test_final_contains_predicates_do_not_fire(declaration_name: str) -> None:
    """Keep final ``contains`` predicates out of the user's naming report.

    Args:
        declaration_name: Containment check the user chose for a scalar Boolean.
    """
    # A user may name a search helper after the relationship it answers.
    user_source = f"def {declaration_name}() -> bool:\n    return True\n"

    user_findings = BooleanPrefixRule().analyse(_unit(user_source), _ctx())

    assert user_findings == []


def test_contains_before_cache_still_fires() -> None:
    """Keep an internal noun token from becoming a global predicate escape."""
    # A user may describe a cached query whose name does not end in a predicate.
    user_source = "def query_contains_cache() -> bool:\n    return True\n"

    user_findings = BooleanPrefixRule().analyse(_unit(user_source), _ctx())

    assert len(user_findings) == 1
    assert user_findings[0].metadata["identifier"] == "query_contains_cache"


def test_internal_has_token_predicate_does_not_fire() -> None:
    """Keep a distinct internal ``has`` predicate out of the naming report."""
    # A user may retain a domain subject before the predicate and its object.
    user_source = "def _query_has_terms() -> bool:\n    return True\n"

    user_findings = BooleanPrefixRule().analyse(_unit(user_source), _ctx())

    assert user_findings == []


@pytest.mark.parametrize(
    "declaration_name",
    [
        pytest.param("hash_value", id="hash"),
        pytest.param("hasher_state", id="hasher"),
    ],
)
def test_internal_has_token_substrings_still_fire(declaration_name: str) -> None:
    """Keep words containing ``has`` visible in the user's naming report.

    Args:
        declaration_name: Non-predicate collision the user placed on a Boolean.
    """
    # A user may describe hashing state without asking a ``has`` question.
    user_source = f"def {declaration_name}() -> bool:\n    return True\n"

    user_findings = BooleanPrefixRule().analyse(_unit(user_source), _ctx())

    assert len(user_findings) == 1
    assert user_findings[0].metadata["identifier"] == declaration_name


@pytest.mark.parametrize(
    "declaration_name",
    ["status", "result", "value"],
    ids=["status", "result", "value"],
)
def test_vague_boolean_names_still_fire(declaration_name: str) -> None:
    """Keep vague scalar names visible in the user's naming report.

    Args:
        declaration_name: Vague result label the user placed on a Boolean.
    """
    # A user may expose a Boolean result without saying which question it answers.
    user_source = f"def {declaration_name}() -> bool:\n    return True\n"

    user_findings = BooleanPrefixRule().analyse(_unit(user_source), _ctx())

    assert len(user_findings) == 1
    assert user_findings[0].metadata["identifier"] == declaration_name


def test_unconfigured_accepted_boolean_name_still_fires() -> None:
    """Guide users until they explicitly preserve an external boundary name."""
    # A user may have a protocol name but has not yet declared that exception.
    user_source = "def publish_index() -> bool:\n    return True\n"

    user_findings = BooleanPrefixRule().analyse(_unit(user_source), _ctx())

    assert len(user_findings) == 1
    assert user_findings[0].metadata["identifier"] == "publish_index"


def test_accepted_boolean_name_keeps_exact_publish_index_boundary() -> None:
    """Preserve only the exact external name selected in user configuration."""
    # A user may keep one protocol method while still reviewing nearby result names.
    user_source = (
        "def publish_index() -> bool:\n"
        "    return True\n"
        "def deploy_result() -> bool:\n"
        "    return True\n"
    )
    configured_context = _ctx(options={"acceptedBooleanNames": ["publish_index"]})

    user_findings = BooleanPrefixRule().analyse(_unit(user_source), configured_context)
    # Each remaining result is a nearby name the user still needs to review.
    user_finding_identifiers = [finding.metadata["identifier"] for finding in user_findings]

    assert user_finding_identifiers == ["deploy_result"]
