"""Render the default ``.gruff-py.yaml`` from the built-in rule registry."""

import tomllib
from collections.abc import Iterable
from pathlib import Path
from typing import Any

import yaml

from gruffpy.config.analysis_config import AnalysisConfig
from gruffpy.config.exceptions import ConfigError
from gruffpy.config.rule_settings import RuleSettings
from gruffpy.config.yaml_loader import load_gruff_py_yaml
from gruffpy.rule.registry import RuleRegistry

_HEADER = (
    "# gruff-py configuration - .gruff-py.yaml\n"
    "# Generated by `gruff-py init`. Mirrors RuleRegistry.defaults() plus starter ignores.\n"
    "# Built-in ignores and .gitignore already apply; add project-specific globs below.\n"
    "# After reviewing findings, `gruff-py analyse . --generate-baseline` records known debt.\n"
    "# See docs/configuration.md for the full key reference.\n"
)

DEFAULT_INIT_IGNORED_PATH_PATTERNS = (
    ".agents/",
    ".antigravitycli/",
    ".claude/",
    ".codex/",
    ".github/",
    ".goat-flow/",
    "tests/fixtures/**",
)


def render_default_config_yaml(existing_ignored_path_patterns: Iterable[str] = ()) -> str:
    """Return the default config serialised as YAML text.

    Args:
        existing_ignored_path_patterns: Existing ``paths.ignore`` entries to preserve
            ahead of the starter init ignores.

    Returns:
        YAML string equivalent to ``AnalysisConfig.from_registry(RuleRegistry.defaults())``,
        with starter ``paths.ignore`` entries, in the shape ``ConfigLoader`` accepts.
    """
    config = AnalysisConfig.from_registry(RuleRegistry.defaults()).with_ignored_path_patterns(
        _merged_init_ignored_path_patterns(existing_ignored_path_patterns)
    )
    document = _document_for(config)
    body = yaml.safe_dump(document, sort_keys=False, default_flow_style=False)
    return _HEADER + body


def existing_ignored_path_patterns(config_path: Path) -> tuple[str, ...]:
    """Return existing ``paths.ignore`` entries from a YAML config file.

    Args:
        config_path: Existing ``.gruff-py.yaml`` path.

    Returns:
        Tuple of existing ignore entries, or an empty tuple when absent.

    Raises:
        ConfigError: When the file cannot be parsed or ``paths.ignore`` is malformed.
    """
    section = load_gruff_py_yaml(config_path)
    paths = section.get("paths", {})
    if paths is None:
        return ()
    if not isinstance(paths, dict):
        raise ConfigError(f"{config_path}: paths must be a mapping to preserve paths.ignore.")
    ignore = paths.get("ignore", [])
    if not isinstance(ignore, list) or not all(isinstance(pattern, str) for pattern in ignore):
        raise ConfigError(f"{config_path}: paths.ignore must be a list of strings.")
    return tuple(ignore)


def _merged_init_ignored_path_patterns(
    existing_ignored_path_patterns: Iterable[str],
) -> tuple[str, ...]:
    merged: list[str] = []
    seen: set[str] = set()
    for pattern in (*existing_ignored_path_patterns, *DEFAULT_INIT_IGNORED_PATH_PATTERNS):
        if pattern in seen:
            continue
        seen.add(pattern)
        merged.append(pattern)
    return tuple(merged)


def _document_for(config: AnalysisConfig) -> dict[str, Any]:
    major, minor = config.minimum_python_version
    return {
        "minimumPythonVersion": f"{major}.{minor}",
        "paths": {"ignore": list(config.ignored_path_patterns)},
        "allowlists": {
            "acceptedAbbreviations": list(config.accepted_abbreviations),
            "secretPreviews": list(config.allowed_secret_previews),
            "deadCode": {
                "symbols": list(config.dead_code_allowlist.symbols),
                "decorators": list(config.dead_code_allowlist.decorators),
                "paths": list(config.dead_code_allowlist.paths),
            },
        },
        "selection": {
            "tiers": list(config.rule_selection.tiers),
            "pillars": list(config.rule_selection.pillars),
            "rules": list(config.rule_selection.rules),
            "excludePillars": list(config.rule_selection.exclude_pillars),
            "excludeRules": list(config.rule_selection.exclude_rules),
        },
        "rules": {rule_id: _rule_entry(config.rules[rule_id]) for rule_id in sorted(config.rules)},
    }


def existing_config_source(project_root: Path) -> Path | None:
    """Return the project's existing gruff config path, or ``None`` if absent.

    Mirrors :class:`gruffpy.config.loader.ConfigLoader` discovery: prefers
    ``.gruff-py.yaml`` / legacy ``.gruff.yaml``, then falls back to
    ``pyproject.toml`` ``[tool.gruff-py]`` / ``[tool.gruff]``. A
    ``pyproject.toml`` that exists but cannot be parsed is reported as the
    existing source so callers do not silently create a competing
    ``.gruff-py.yaml`` that would mask the original TOML error.

    Args:
        project_root: Directory checked for config files.

    Returns:
        Path to the discovered config source, or ``None`` when none exists.
    """
    for name in (".gruff-py.yaml", ".gruff.yaml"):
        candidate = project_root / name
        if candidate.exists():
            return candidate
    pyproject = project_root / "pyproject.toml"
    if not pyproject.exists():
        return None
    try:
        with open(pyproject, "rb") as f:
            data = tomllib.load(f)
    except OSError:
        return pyproject
    except tomllib.TOMLDecodeError:
        return pyproject
    tool = data.get("tool")
    if not isinstance(tool, dict):
        return None
    if "gruff-py" in tool or "gruff" in tool:
        return pyproject
    return None


def _rule_entry(settings: RuleSettings) -> dict[str, Any]:
    entry: dict[str, Any] = {"enabled": settings.enabled}
    if settings.thresholds:
        entry["thresholds"] = dict(settings.thresholds)
    if settings.options:
        entry["options"] = dict(settings.options)
    return entry
